### PR TITLE
Schema and seed

### PR DESCRIPTION
**Pull request by imartinez8**
Created a schema and seeded database

### CODE REVIEW

**Comment by imartinez8** [comment]
- weird... i see that on the PR but not on my code. I will see if I can fix it.
- for now I didn't use any unique or foreign, ill add them to next PR
- i will be using mervins dummy product but just one item... the others apparently aren't necessary.

**Comment by dkancalade** [comment]
Ok sounds good then.

**Comment by RobResnick** [comment]
Updated.

**Comment by imartinez8** [comment]
Updated

**Pull request merged**
